//! StellarTix — Soroban Contract Tests
//!
//! Exactly 3 tests covering the MVP transaction flow:
//! 1. Happy path: Issue a ticket and verify it successfully
//! 2. Edge case:  Duplicate ticket issuance is rejected
//! 3. State:      On-chain storage reflects correct owner and hash after issuance

#[cfg(test)]
mod tests {
    use soroban_sdk::{
        testutils::Address as _,
        Address, Env, String,
    };

    // Import the contract and its client (generated by soroban_sdk macros)
    use crate::{StellarTixContract, StellarTixContractClient};

    // ─── Shared test helpers ─────────────────────────────────────────────────

    /// Deploys and initializes a fresh contract instance.
    /// Returns (env, client, admin_address).
    fn setup() -> (Env, StellarTixContractClient<'static>, Address) {
        let env = Env::default();
        // Mock all auth checks so tests don't need real signatures
        env.mock_all_auths();

        let contract_id = env.register_contract(None, StellarTixContract);
        let client = StellarTixContractClient::new(&env, &contract_id);

        let admin = Address::generate(&env);
        client.initialize(&admin);

        (env, client, admin)
    }

    /// Issues a standard test ticket through the client.
    fn issue_test_ticket(
        env: &Env,
        client: &StellarTixContractClient,
        ticket_id: &str,
        owner: &Address,
    ) {
        client.issue_ticket(
            &String::from_str(env, ticket_id),
            owner,
            &String::from_str(env, "Eraserheads Reunion Concert"),
            &1_780_000_000u64,                     // Unix timestamp
            &String::from_str(env, "FLOOR-A12"),
            &500_000_000i128,                       // 50 XLM in stroops
            &750_000_000i128,                       // 75 XLM max resale cap
            &String::from_str(env, "abc123hash"),
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TEST 1 — Happy Path
    // A ticket is issued successfully and verify_ticket returns true.
    // This proves the end-to-end MVP flow works: issue → verify → true.
    // ─────────────────────────────────────────────────────────────────────────
    #[test]
    fn test_happy_path_issue_and_verify() {
        let (env, client, _admin) = setup();
        let buyer = Address::generate(&env);

        // Issue the ticket
        issue_test_ticket(&env, &client, "EVT2025-0001", &buyer);

        // Verify with the correct integrity hash — should return true
        let is_valid = client.verify_ticket(
            &String::from_str(&env, "EVT2025-0001"),
            &String::from_str(&env, "abc123hash"),
        );

        assert!(is_valid, "Ticket should be valid after issuance");

        // Verify with a wrong hash — should return false (tamper detected)
        let is_tampered = client.verify_ticket(
            &String::from_str(&env, "EVT2025-0001"),
            &String::from_str(&env, "WRONG_HASH"),
        );

        assert!(!is_tampered, "Tampered ticket should fail verification");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TEST 2 — Edge Case: Duplicate issuance is rejected
    // Issuing the same ticket_id twice must panic with "ticket_already_exists".
    // This prevents counterfeit duplicates from entering the system.
    // ─────────────────────────────────────────────────────────────────────────
    #[test]
    #[should_panic(expected = "ticket_already_exists")]
    fn test_duplicate_ticket_rejected() {
        let (env, client, _admin) = setup();
        let buyer = Address::generate(&env);

        // First issuance — should succeed
        issue_test_ticket(&env, &client, "EVT2025-0002", &buyer);

        // Second issuance with the same ticket_id — must panic
        issue_test_ticket(&env, &client, "EVT2025-0002", &buyer);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TEST 3 — State Verification
    // After issuance, contract storage must reflect the correct owner, seat,
    // event name, integrity hash, and is_used = false.
    // ─────────────────────────────────────────────────────────────────────────
    #[test]
    fn test_state_reflects_correct_data_after_issuance() {
        let (env, client, _admin) = setup();
        let buyer = Address::generate(&env);

        issue_test_ticket(&env, &client, "EVT2025-0003", &buyer);

        // Fetch the stored ticket and assert every field
        let ticket = client.get_ticket(
            &String::from_str(&env, "EVT2025-0003"),
        );

        assert_eq!(ticket.owner, buyer, "Owner must match buyer address");
        assert_eq!(
            ticket.seat,
            String::from_str(&env, "FLOOR-A12"),
            "Seat must match issued value"
        );
        assert_eq!(
            ticket.event_name,
            String::from_str(&env, "Eraserheads Reunion Concert"),
            "Event name must match"
        );
        assert_eq!(
            ticket.integrity_hash,
            String::from_str(&env, "abc123hash"),
            "Integrity hash must be stored as-is"
        );
        assert!(!ticket.is_used, "Newly issued ticket must not be marked as used");
        assert!(!ticket.for_sale, "Newly issued ticket must not be listed for resale");
        assert_eq!(ticket.issue_price, 500_000_000i128, "Issue price must match");

        // Confirm global ticket count incremented
        let count = client.get_ticket_count();
        assert_eq!(count, 1u32, "Ticket count must be 1 after single issuance");
    }
}//! StellarTix — Soroban Contract Tests
//!
//! Exactly 3 tests covering the MVP transaction flow:
//! 1. Happy path: Issue a ticket and verify it successfully
//! 2. Edge case:  Duplicate ticket issuance is rejected
//! 3. State:      On-chain storage reflects correct owner and hash after issuance

#[cfg(test)]
mod tests {
    use soroban_sdk::{
        testutils::Address as _,
        Address, Env, String,
    };

    // Import the contract and its client (generated by soroban_sdk macros)
    use crate::{StellarTixContract, StellarTixContractClient};

    // ─── Shared test helpers ─────────────────────────────────────────────────

    /// Deploys and initializes a fresh contract instance.
    /// Returns (env, client, admin_address).
    fn setup() -> (Env, StellarTixContractClient<'static>, Address) {
        let env = Env::default();
        // Mock all auth checks so tests don't need real signatures
        env.mock_all_auths();

        let contract_id = env.register_contract(None, StellarTixContract);
        let client = StellarTixContractClient::new(&env, &contract_id);

        let admin = Address::generate(&env);
        client.initialize(&admin);

        (env, client, admin)
    }

    /// Issues a standard test ticket through the client.
    fn issue_test_ticket(
        env: &Env,
        client: &StellarTixContractClient,
        ticket_id: &str,
        owner: &Address,
    ) {
        client.issue_ticket(
            &String::from_str(env, ticket_id),
            owner,
            &String::from_str(env, "Eraserheads Reunion Concert"),
            &1_780_000_000u64,                     // Unix timestamp
            &String::from_str(env, "FLOOR-A12"),
            &500_000_000i128,                       // 50 XLM in stroops
            &750_000_000i128,                       // 75 XLM max resale cap
            &String::from_str(env, "abc123hash"),
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TEST 1 — Happy Path
    // A ticket is issued successfully and verify_ticket returns true.
    // This proves the end-to-end MVP flow works: issue → verify → true.
    // ─────────────────────────────────────────────────────────────────────────
    #[test]
    fn test_happy_path_issue_and_verify() {
        let (env, client, _admin) = setup();
        let buyer = Address::generate(&env);

        // Issue the ticket
        issue_test_ticket(&env, &client, "EVT2025-0001", &buyer);

        // Verify with the correct integrity hash — should return true
        let is_valid = client.verify_ticket(
            &String::from_str(&env, "EVT2025-0001"),
            &String::from_str(&env, "abc123hash"),
        );

        assert!(is_valid, "Ticket should be valid after issuance");

        // Verify with a wrong hash — should return false (tamper detected)
        let is_tampered = client.verify_ticket(
            &String::from_str(&env, "EVT2025-0001"),
            &String::from_str(&env, "WRONG_HASH"),
        );

        assert!(!is_tampered, "Tampered ticket should fail verification");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TEST 2 — Edge Case: Duplicate issuance is rejected
    // Issuing the same ticket_id twice must panic with "ticket_already_exists".
    // This prevents counterfeit duplicates from entering the system.
    // ─────────────────────────────────────────────────────────────────────────
    #[test]
    #[should_panic(expected = "ticket_already_exists")]
    fn test_duplicate_ticket_rejected() {
        let (env, client, _admin) = setup();
        let buyer = Address::generate(&env);

        // First issuance — should succeed
        issue_test_ticket(&env, &client, "EVT2025-0002", &buyer);

        // Second issuance with the same ticket_id — must panic
        issue_test_ticket(&env, &client, "EVT2025-0002", &buyer);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TEST 3 — State Verification
    // After issuance, contract storage must reflect the correct owner, seat,
    // event name, integrity hash, and is_used = false.
    // ─────────────────────────────────────────────────────────────────────────
    #[test]
    fn test_state_reflects_correct_data_after_issuance() {
        let (env, client, _admin) = setup();
        let buyer = Address::generate(&env);

        issue_test_ticket(&env, &client, "EVT2025-0003", &buyer);

        // Fetch the stored ticket and assert every field
        let ticket = client.get_ticket(
            &String::from_str(&env, "EVT2025-0003"),
        );

        assert_eq!(ticket.owner, buyer, "Owner must match buyer address");
        assert_eq!(
            ticket.seat,
            String::from_str(&env, "FLOOR-A12"),
            "Seat must match issued value"
        );
        assert_eq!(
            ticket.event_name,
            String::from_str(&env, "Eraserheads Reunion Concert"),
            "Event name must match"
        );
        assert_eq!(
            ticket.integrity_hash,
            String::from_str(&env, "abc123hash"),
            "Integrity hash must be stored as-is"
        );
        assert!(!ticket.is_used, "Newly issued ticket must not be marked as used");
        assert!(!ticket.for_sale, "Newly issued ticket must not be listed for resale");
        assert_eq!(ticket.issue_price, 500_000_000i128, "Issue price must match");

        // Confirm global ticket count incremented
        let count = client.get_ticket_count();
        assert_eq!(count, 1u32, "Ticket count must be 1 after single issuance");
    }
}